name: ai_que_fome_flutter
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  supabase_flutter: ^2.5.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/images/
  module:
    androidX: true
    androidPackage: com.example.ai_que_fome_flutter
    iosBundleIdentifier: com.example.aiQueFomeFlutter
